name: merge

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
      id: go

    - name: checkout code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: install libpcap
      run: |
       apt-get update && \
         apt-get install -y --no-install-recommends \
         gcc \
         libpcap-dev \
         make

    - name: run tests
      run: |
        make test
